INSERT INTO departments (id, name, description, is_active, is_deleted, created_at, updated_at) 
VALUES ('dept-01', 'Finance', 'Finance departemen', true, false, toTimestamp(now()), toTimestamp(now()));

INSERT INTO departments (id, name, description, is_active, is_deleted, created_at, updated_at) 
VALUES ('dept-02', 'Human Resource', 'Human resource departemen', true, false, toTimestamp(now()), toTimestamp(now()));

INSERT INTO departments (id, name, description, is_active, is_deleted, created_at, updated_at) 
VALUES ('dept-03', 'Marketing', 'Marketing departemen', true, false, toTimestamp(now()), toTimestamp(now()));

INSERT INTO departments (id, name, description, is_active, is_deleted, created_at, updated_at) 
VALUES ('dept-04', 'Operational', 'Operational departemen', true, false, toTimestamp(now()), toTimestamp(now()));

INSERT INTO departments (id, name, description, is_active, is_deleted, created_at, updated_at) 
VALUES ('dept-05', 'Warehouse', 'Warehouse departemen', true, false, toTimestamp(now()), toTimestamp(now()));